# Generated by Django 4.0.3 on 2022-04-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='teams',
            field=models.ManyToManyField(related_name='seasons', through='football_app.SeasonTable', to='football_app.team'),
        ),
    ]
