# Generated by Django 4.0.3 on 2022-04-18 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0002_alter_season_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='league',
        ),
        migrations.AddField(
            model_name='team',
            name='actuall_league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='football_app.league', verbose_name='Aktulna liga'),
        ),
        migrations.AddField(
            model_name='team',
            name='actuall_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='football_app.season', verbose_name='Aktualny sezon'),
        ),
    ]
