# Generated by Django 4.0.3 on 2022-04-18 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0003_remove_team_league_team_actuall_league_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='teams',
            new_name='season_table',
        ),
        migrations.AlterField(
            model_name='seasontable',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_tables', to='football_app.season', verbose_name='Sezon'),
        ),
        migrations.AlterField(
            model_name='seasontable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_tables', to='football_app.team', verbose_name='Drużyna'),
        ),
        migrations.AlterField(
            model_name='team',
            name='actuall_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='football_app.season', verbose_name='Aktualny sezon'),
        ),
    ]
